### ISSUE TITLE
Tables seem to be broken

### ISSUE THREAD

**Issue by Ik1497** [getfider/fider.io#40]
https://fider.io/docs/api

![C7CA2E18-950A-44C9-8973-E11DA5DF07E5](https://user-images.githubusercontent.com/113038466/213888989-0a373428-0747-4f04-9c68-9945fb7f95e1.jpeg)

**Comment by alcalyn** [comment]
Seems to be fixed
![image](https://github.com/getfider/fider.io/assets/1588144/19b3a75e-1f85-4ed5-aeb4-98d78238fa49)
